services:
  # Servicio de MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-network
    restart: always

  # Servicio de Nginx (servidor web)
  web:
    image: nginx:latest
    container_name: nginx-serverjenkins
    ports:
      - "${WEB_SERVER_PORT}:80"
    volumes:
      - ./public:/usr/share/nginx/html  # Carpeta de archivos estáticos
    networks:
      - dev-network
    depends_on:
      - mysql
    restart: always

networks:
  dev-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
